#define ALIGN(I, A) (((I)+(A)-1)/(A)*(A))
! (C) Copyright 2000- ECMWF.
! (C) Copyright 2000- Meteo-France.
! (C) Copyright 2022- NVIDIA.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE TRLTOM_PACK_UNPACK
  USE BUFFERED_ALLOCATOR_MOD, ONLY: ALLOCATION_RESERVATION_HANDLE
  USE PARKIND_ECTRANS,        ONLY: JPIM
  IMPLICIT NONE

  PRIVATE
  PUBLIC :: TRLTOM_PACK_HANDLE, PREPARE_TRLTOM_PACK, TRLTOM_PACK
  PUBLIC :: TRLTOM_UNPACK_HANDLE, PREPARE_TRLTOM_UNPACK, TRLTOM_UNPACK

  TYPE TRLTOM_PACK_HANDLE
    TYPE(ALLOCATION_RESERVATION_HANDLE) :: HFOUBUF_IN
  END TYPE
  TYPE TRLTOM_UNPACK_HANDLE
    TYPE(ALLOCATION_RESERVATION_HANDLE) :: HINPS_AND_ZINPA
  END TYPE

  INTEGER(KIND=JPIM) :: A = 8 !Alignment

CONTAINS
  FUNCTION PREPARE_TRLTOM_PACK(ALLOCATOR, KF_FS) RESULT(HTRLTOM_PACK)
    USE PARKIND_ECTRANS,        ONLY: JPIM, JPRBT, JPIB
    USE TPM_DISTR,              ONLY: D
    USE ISO_C_BINDING,          ONLY: C_SIZEOF
    USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR, RESERVE

    IMPLICIT NONE

    TYPE(BUFFERED_ALLOCATOR), INTENT(INOUT) :: ALLOCATOR
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_FS
    TYPE(TRLTOM_PACK_HANDLE) :: HTRLTOM_PACK

    REAL(KIND=JPRBT) :: DUMMY

    HTRLTOM_PACK%HFOUBUF_IN = RESERVE(ALLOCATOR, 2_JPIB*D%NLENGT0B*KF_FS*C_SIZEOF(DUMMY), "HTRLTOM_PACK%HFOUBUF_IN")
  END FUNCTION PREPARE_TRLTOM_PACK

  SUBROUTINE TRLTOM_PACK(ALLOCATOR,HTRLTOM_PACK,PREEL_COMPLEX,FOUBUF_IN,KF_FS)
    !**** *TRLTOM_PACK* - Copy fourier data from local array to buffer

    !     Purpose.
    !     --------
    !        Routine for copying fourier data from local array to buffer

    !**   Interface.
    !     ----------
    !     CALL TRLTOM_PACK(...)

    !     Explicit arguments :  PREEL - local fourier/GP array
    !     --------------------  KF_FS - number of fields
    !
    !     Externals.  None.
    !     ----------

    !     Author.
    !     -------
    !        Mats Hamrud *ECMWF*

    !     ------------------------------------------------------------------

    USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR, ASSIGN_PTR, GET_ALLOCATION
    USE PARKIND_ECTRANS,        ONLY: JPIM, JPRBT, JPIB
    USE TPM_DISTR,              ONLY: D, MYSETW
    USE TPM_GEOMETRY,           ONLY: G
    USE TPM_DIM,                ONLY: R
    USE ISO_C_BINDING,          ONLY: C_SIZEOF
    !

    IMPLICIT NONE

    ! CONTIGUOUS so this can be sequence-associated with the explicit-shape dummy of
    ! TRLTOM_PACK_KERNEL without the compiler allowing for a packing temporary.
    REAL(KIND=JPRBT), INTENT(IN), CONTIGUOUS :: PREEL_COMPLEX(:)
    REAL(KIND=JPRBT), POINTER, INTENT(OUT) :: FOUBUF_IN(:)
    INTEGER(KIND=JPIM),INTENT(IN) :: KF_FS
    TYPE(BUFFERED_ALLOCATOR), INTENT(IN) :: ALLOCATOR
    TYPE(TRLTOM_PACK_HANDLE), INTENT(IN) :: HTRLTOM_PACK

    ! An element of a non-CONTIGUOUS pointer array may not be sequence-associated with an
    ! explicit-shape dummy (F2018 15.5.2.4); this alias addresses the same allocator slab.
    REAL(KIND=JPRBT), POINTER, CONTIGUOUS :: ZFOUBUF_IN_C(:)

    INTEGER(KIND=JPIM) :: JM,JF,IGLG,OFFSET_VAR,KGL
    INTEGER(KIND=JPIB) :: IOFF_LAT,ISTA, NMEN_MAX

    REAL(KIND=JPRBT)    :: SCAL

    ASSOCIATE(D_NSTAGTF=>D%NSTAGTF, D_NPNTGTB0=>D%NPNTGTB0, D_NPTRLS=>D%NPTRLS, &
            & D_NDGL_FS=>D%NDGL_FS, G_NMEN=>G%NMEN, G_NLOEN=>G%NLOEN, R_NSMAX=>R%NSMAX)

    CALL ASSIGN_PTR(FOUBUF_IN, GET_ALLOCATION(ALLOCATOR, HTRLTOM_PACK%HFOUBUF_IN),&
        & 1_JPIB, 2_JPIB*D%NLENGT0B*KF_FS*C_SIZEOF(FOUBUF_IN(1)))

#ifdef OMPGPU
   ! FOUBUF_IN/PREEL_COMPLEX are growing-allocator buffers. Their storage is registered
   ! with omp_target_associate_ptr, so ordinary mapping resolves it, but their descriptors
   ! are never in the present table and so cannot be MAP(PRESENT)'d.
   ! G, D and R are reached only through their ASSOCIATE aliases. Naming the parent types here
   ! makes the runtime walk every allocatable component of those derived types and re-copy each
   ! component descriptor on entry, so only the aliases are mapped.
   !$OMP TARGET DATA MAP(ECTRANS_MAP_PRESENT_ALLOC:G_NMEN,D_NPNTGTB0,D_NSTAGTF,&
   !$OMP& D_NDGL_FS,G_NLOEN,R_NSMAX)
#endif
#ifdef ACCGPU
    !$ACC DATA PRESENT(G,G_NMEN,D,D_NPNTGTB0,FOUBUF_IN,PREEL_COMPLEX,D_NSTAGTF,D_NDGL_FS,G_NLOEN, R,R_NSMAX) ASYNC(1)
#endif

    ! scale results and move into next transformation buffer

    OFFSET_VAR=D_NPTRLS(MYSETW)
    
    NMEN_MAX=MAXVAL(G_NMEN)

    ZFOUBUF_IN_C => FOUBUF_IN

    CALL TRLTOM_PACK_KERNEL(PREEL_COMPLEX,SIZE(PREEL_COMPLEX,KIND=JPIB), &
      &                     ZFOUBUF_IN_C(1),SIZE(FOUBUF_IN,KIND=JPIB), &
      &                     G_NMEN,G_NLOEN,SIZE(G_NMEN), &
      &                     D_NPNTGTB0,SIZE(D_NPNTGTB0,1)-1, &
      &                     D_NSTAGTF,SIZE(D_NSTAGTF), &
      &                     D_NDGL_FS,KF_FS,OFFSET_VAR,NMEN_MAX)
#ifdef ACCGPU
    !$ACC END DATA

    !$ACC WAIT(1)
#endif
#ifdef OMPGPU
    !$OMP END TARGET DATA
#endif
    END ASSOCIATE
  END SUBROUTINE TRLTOM_PACK

  FUNCTION PREPARE_TRLTOM_UNPACK(ALLOCATOR, KF_FS) RESULT(HTRLTOM_UNPACK)
    USE PARKIND_ECTRANS,        ONLY: JPIM, JPRBT, JPRD, JPIB
    USE BUFFERED_ALLOCATOR_MOD, ONLY: BUFFERED_ALLOCATOR, RESERVE
    USE LEDIR_MOD,              ONLY: LEDIR_STRIDES
    USE ISO_C_BINDING,          ONLY: C_SIZEOF

    IMPLICIT NONE

    TYPE(BUFFERED_ALLOCATOR), INTENT(INOUT) :: ALLOCATOR
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_FS
    TYPE(TRLTOM_UNPACK_HANDLE) :: HTRLTOM_UNPACK

    INTEGER(KIND=JPIM)  :: IIN_STRIDES0
    INTEGER(KIND=JPIB)  :: IIN_SIZE
    INTEGER(KIND=JPIM)  :: IIN0_STRIDES0, IIN0_SIZE
    INTEGER(KIND=JPIB)  :: ISIZE

    REAL(KIND=JPRBT) :: ZPRBT_DUMMY
    REAL(KIND=JPRD) :: ZPRD_DUMMY

    CALL LEDIR_STRIDES(KF_FS,IIN_STRIDES0=IIN_STRIDES0,IIN_SIZE=IIN_SIZE,&
                       IIN0_STRIDES0=IIN0_STRIDES0,IIN0_SIZE=IIN0_SIZE)

    ! Check if the reuse buffer is large enough
    ISIZE = ALIGN(IIN_SIZE*C_SIZEOF(ZPRBT_DUMMY),128)
    ISIZE = ISIZE + ALIGN(IIN_SIZE*C_SIZEOF(ZPRBT_DUMMY),128)
    ISIZE = ISIZE + ALIGN(IIN0_SIZE*C_SIZEOF(ZPRD_DUMMY),128)
    ISIZE = ISIZE + ALIGN(IIN0_SIZE*C_SIZEOF(ZPRD_DUMMY),128)

    HTRLTOM_UNPACK%HINPS_AND_ZINPA = RESERVE(ALLOCATOR, ISIZE, "HTRLTOM_UNPACK%HINPS_AND_ZINPA")
  END FUNCTION PREPARE_TRLTOM_UNPACK

  SUBROUTINE TRLTOM_UNPACK(ALLOCATOR,HTRLTOM_UNPACK,FOUBUF,ZINPS,ZINPA,ZINPS0,ZINPA0,KF_FS,KF_UV)
    USE PARKIND_ECTRANS,             ONLY: JPIM, JPRBT, JPRD, JPIB
    USE TPM_DIM,                     ONLY: R
    USE TPM_GEOMETRY,                ONLY: G
    USE BUFFERED_ALLOCATOR_MOD,      ONLY: BUFFERED_ALLOCATOR, ASSIGN_PTR, GET_ALLOCATION
    USE TPM_FIELDS,                  ONLY: F
    USE TPM_DISTR,                   ONLY: D
    USE LEDIR_MOD,                   ONLY: LEDIR_STRIDES
    USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_SIZEOF

    IMPLICIT NONE

    ! CONTIGUOUS so this can be sequence-associated with the explicit-shape dummy of
    ! TRLTOM_UNPACK_KERNEL without the compiler allowing for a packing temporary.
    REAL(KIND=JPRBT), INTENT(IN), CONTIGUOUS :: FOUBUF(:)
    REAL(KIND=JPRBT), POINTER, INTENT(INOUT) :: ZINPS(:), ZINPA(:)
    REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: ZINPS0(:), ZINPA0(:)
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_FS, KF_UV
    TYPE(BUFFERED_ALLOCATOR), INTENT(IN) :: ALLOCATOR
    TYPE(TRLTOM_UNPACK_HANDLE), INTENT(IN) :: HTRLTOM_UNPACK

    REAL(KIND=JPRBT), POINTER :: PREEL_COMPLEX(:)

    ! An element of a non-CONTIGUOUS pointer array may not be sequence-associated with an
    ! explicit-shape dummy (F2018 15.5.2.4); these alias the same allocator slabs.
    REAL(KIND=JPRBT), POINTER, CONTIGUOUS :: ZINPS_C(:), ZINPA_C(:)
    REAL(KIND=JPRD), POINTER, CONTIGUOUS :: ZINPS0_C(:), ZINPA0_C(:)

    INTEGER(KIND=JPIM) :: IIN_STRIDES0
    INTEGER(KIND=JPIB) :: IIN_SIZE
    INTEGER(KIND=JPIM) :: IIN0_STRIDES0, IIN0_SIZE

    INTEGER(KIND=JPIB) :: IALLOC_POS, IALLOC_SZ

    INTEGER(KIND=JPIB)  :: JF, OFFSET1, OFFSET2
    INTEGER(KIND=JPIM) :: KM, ISL, IGLS, JGL, KMLOC

    REAL(KIND=JPRBT) :: PAIA, PAIS

    ASSOCIATE(D_NUMP=>D%NUMP, R_NDGNH=>R%NDGNH, R_NDGL=>R%NDGL, F_RW=>F%RW, F_RACTHE=>F%RACTHE, &
            & D_MYMS=>D%MYMS, D_NPNTGTB1=>D%NPNTGTB1, D_OFFSETS_GEMM1=>D%OFFSETS_GEMM1, &
            & G_NDGLU=>G%NDGLU)
    CALL LEDIR_STRIDES(KF_FS,IIN_STRIDES0=IIN_STRIDES0,IIN_SIZE=IIN_SIZE,&
                       IIN0_STRIDES0=IIN0_STRIDES0,IIN0_SIZE=IIN0_SIZE)

    IALLOC_POS=1

    IALLOC_SZ = ALIGN(IIN_SIZE*C_SIZEOF(ZINPS(0)),128)
    CALL ASSIGN_PTR(ZINPS, GET_ALLOCATION(ALLOCATOR, HTRLTOM_UNPACK%HINPS_AND_ZINPA),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS=IALLOC_POS+IALLOC_SZ

    IALLOC_SZ = ALIGN(IIN_SIZE*C_SIZEOF(ZINPA(0)),128)
    CALL ASSIGN_PTR(ZINPA, GET_ALLOCATION(ALLOCATOR, HTRLTOM_UNPACK%HINPS_AND_ZINPA),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS=IALLOC_POS+IALLOC_SZ

    IALLOC_SZ = ALIGN(IIN0_SIZE*C_SIZEOF(ZINPS0(0)),128)
    CALL ASSIGN_PTR(ZINPS0, GET_ALLOCATION(ALLOCATOR, HTRLTOM_UNPACK%HINPS_AND_ZINPA),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS=IALLOC_POS+IALLOC_SZ

    IALLOC_SZ = ALIGN(IIN0_SIZE*C_SIZEOF(ZINPA0(0)),128)
    CALL ASSIGN_PTR(ZINPA0, GET_ALLOCATION(ALLOCATOR, HTRLTOM_UNPACK%HINPS_AND_ZINPA),&
        & IALLOC_POS, IALLOC_SZ)
    IALLOC_POS=IALLOC_POS+IALLOC_SZ

#ifdef OMPGPU
    ! ZINPS/ZINPA/ZINPS0/ZINPA0 (GEMM input buffers) and FOUBUF are growing-allocator
    ! buffers. Their storage is registered with omp_target_associate_ptr, so ordinary
    ! mapping resolves it and they stay in SHARED; only their descriptors are absent from
    ! the present table, which is why they cannot be MAP(PRESENT)'d.
    ! F, D, R and G are reached only through their ASSOCIATE aliases. Naming the parent types
    ! here makes the runtime walk every allocatable component of those derived types and re-copy
    ! each component descriptor on entry, so only the aliases are mapped.
    !$OMP TARGET DATA MAP(ECTRANS_MAP_PRESENT_ALLOC:F_RW,F_RACTHE) &
    !$OMP& MAP(ECTRANS_MAP_PRESENT_ALLOC:D_MYMS,D_NUMP,R_NDGNH,R_NDGL,G_NDGLU) &
    !$OMP& MAP(ECTRANS_MAP_PRESENT_ALLOC:D_NPNTGTB1,D_OFFSETS_GEMM1)

#endif
#ifdef ACCGPU
    !$ACC DATA &
    !$ACC& PRESENT(ZINPS,ZINPA,ZINPS0,ZINPA0) &
    !$ACC& PRESENT(F,F_RW,F_RACTHE) &
    !$ACC& PRESENT(D,D_MYMS,D_NUMP,R,R_NDGNH,R_NDGL,G,G_NDGLU) &
    !$ACC& PRESENT(D_NPNTGTB1,D_OFFSETS_GEMM1,FOUBUF)
#endif

    ZINPS_C => ZINPS
    ZINPA_C => ZINPA
    ZINPS0_C => ZINPS0
    ZINPA0_C => ZINPA0

    CALL TRLTOM_UNPACK_KERNEL(FOUBUF,SIZE(FOUBUF,KIND=JPIB), &
      &                       ZINPS_C(1),ZINPA_C(1),SIZE(ZINPS,KIND=JPIB), &
      &                       ZINPS0_C(1),ZINPA0_C(1),SIZE(ZINPS0,KIND=JPIB), &
      &                       D_MYMS,D_OFFSETS_GEMM1,D_NPNTGTB1,D_NUMP,R_NDGL, &
      &                       G_NDGLU,SIZE(G_NDGLU)-1, &
      &                       F_RW,F_RACTHE,SIZE(F_RW), &
      &                       KF_FS,KF_UV,R_NDGNH,IIN_STRIDES0,IIN0_STRIDES0)

#if defined(USE_CUTLASS) && defined(USE_CUTLASS_3XTF32)
#ifdef OMPGPU
    !$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO COLLAPSE(2) PRIVATE(KM) ECTRANS_OMP_DEFAULT_CLAUSE &
    !$OMP& ECTRANS_DEVICE_ADDR_CLAUSE(ZINPA,ZINPS) &
    !$OMP& ECTRANS_LOOP_BOUNDS_CLAUSE(KF_FS) FIRSTPRIVATE(IIN_STRIDES0)
#endif
#ifdef ACCGPU
    !$ACC PARALLEL LOOP DEFAULT(NONE) COLLAPSE(2) PRIVATE(KM,JGL) &
    !$ACC&              FIRSTPRIVATE(KF_FS,IIN_STRIDES0) ASYNC(1)
#endif
    DO KMLOC=1,D_NUMP
      DO JF=1,KF_FS*2
          KM = D_MYMS(KMLOC)
#ifdef ACCGPU
          !$ACC LOOP SEQ
#endif
          DO JGL=G_NDGLU(KM),ALIGN(G_NDGLU(KM),A)-1
            IF (KM /= 0) THEN
              ZINPA(JF+JGL*IIN_STRIDES0+IIN_STRIDES0*D_OFFSETS_GEMM1(KMLOC))=0.0_JPRB
              ZINPS(JF+JGL*IIN_STRIDES0+IIN_STRIDES0*D_OFFSETS_GEMM1(KMLOC))=0.0_JPRB
            ENDIF
          ENDDO
      ENDDO
    END DO
#endif

#ifdef OMPGPU
    !$OMP END TARGET DATA
#endif
#ifdef ACCGPU
    !$ACC END DATA
#endif

   END ASSOCIATE
  END SUBROUTINE TRLTOM_UNPACK

  ! Pack and unpack bodies with explicit-shape dummy arguments. A POINTER or assumed-shape
  ! actual is described by a dope vector, and the compiler places that dope vector in the
  ! device data environment on every launch: create map entry, copy 48 bytes, tear it down.
  ! Explicit shape carries the extents as FIRSTPRIVATE scalars, so nothing is copied.
  SUBROUTINE TRLTOM_PACK_KERNEL(PREEL_COMPLEX,KREEL,PFOUBUF_IN,KFOUBUF_IN, &
    &                           KNMEN,KNLOEN,KNDGL, &
    &                           KNPNTGTB0,KNSMAX, &
    &                           KNSTAGTF,KNSTAGTF_N, &
    &                           KNDGL_FS,KF_FS,KOFFSET_VAR,KNMEN_MAX)
    USE PARKIND_ECTRANS, ONLY: JPIM, JPRBT, JPIB

    IMPLICIT NONE

    INTEGER(KIND=JPIB), INTENT(IN)  :: KREEL, KFOUBUF_IN, KNMEN_MAX
    INTEGER(KIND=JPIM), INTENT(IN)  :: KNDGL, KNSMAX, KNSTAGTF_N
    INTEGER(KIND=JPIM), INTENT(IN)  :: KNDGL_FS, KF_FS, KOFFSET_VAR
    REAL(KIND=JPRBT),   INTENT(IN)  :: PREEL_COMPLEX(KREEL)
    REAL(KIND=JPRBT),   INTENT(OUT) :: PFOUBUF_IN(KFOUBUF_IN)
    INTEGER(KIND=JPIM), INTENT(IN)  :: KNMEN(KNDGL), KNLOEN(KNDGL)
    INTEGER(KIND=JPIM), INTENT(IN)  :: KNPNTGTB0(0:KNSMAX,KNDGL_FS)
    INTEGER(KIND=JPIB), INTENT(IN)  :: KNSTAGTF(KNSTAGTF_N)

    INTEGER(KIND=JPIM) :: JM, JF, IGLG, KGL
    INTEGER(KIND=JPIB) :: IOFF_LAT, ISTA
    REAL(KIND=JPRBT) :: SCAL

#ifdef OMPGPU
    !$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO COLLAPSE(3) PRIVATE(IGLG,IOFF_LAT,ISTA,SCAL) &
    !$OMP& ECTRANS_DEVICE_ADDR_CLAUSE(PREEL_COMPLEX,PFOUBUF_IN) ECTRANS_LOOP_BOUNDS_CLAUSE(KF_FS) &
    !$OMP& MAP(ECTRANS_MAP_PRESENT_ALLOC:KNMEN,KNLOEN,KNPNTGTB0,KNSTAGTF) &
    !$OMP& FIRSTPRIVATE(KOFFSET_VAR)
#endif
#ifdef ACCGPU
    !$ACC PARALLEL LOOP PRIVATE(IGLG,IOFF_LAT,ISTA,SCAL) FIRSTPRIVATE(KF_FS,KOFFSET_VAR) &
    !$ACC& PRESENT(KNMEN,KNLOEN,KNPNTGTB0,KNSTAGTF) &
    !$ACC& TILE(32,16,1) DEFAULT(NONE) &
#ifndef _CRAYFTN
    !$ACC& ASYNC(1)
#else
    !$ACC&
#endif
#endif
    DO KGL=1,KNDGL_FS
      DO JM=0,KNMEN_MAX
        DO JF=1,KF_FS
          IGLG = KOFFSET_VAR+KGL-1
          IF (JM <= KNMEN(IGLG)) THEN
            IOFF_LAT = KF_FS*KNSTAGTF(KGL)+(JF-1)*(KNSTAGTF(KGL+1)-KNSTAGTF(KGL))

            SCAL = 1._JPRBT/REAL(KNLOEN(IGLG),JPRBT)
            ISTA  = 2_JPIB*KNPNTGTB0(JM,KGL)*KF_FS

            PFOUBUF_IN(ISTA+2*JF-1) = SCAL * PREEL_COMPLEX(IOFF_LAT+2*JM+1)
            PFOUBUF_IN(ISTA+2*JF  ) = SCAL * PREEL_COMPLEX(IOFF_LAT+2*JM+2)
          ENDIF
        ENDDO
      ENDDO
    ENDDO
  END SUBROUTINE TRLTOM_PACK_KERNEL

  SUBROUTINE TRLTOM_UNPACK_KERNEL(PFOUBUF,KFOUBUF,PZINPS,PZINPA,KIN_SIZE, &
    &                             PZINPS0,PZINPA0,KIN0_SIZE, &
    &                             KMYMS,KOFFSETS_GEMM1,KNPNTGTB1,KNUMP,KNDGL, &
    &                             KNDGLU,KNSMAX, &
    &                             PRW,PRACTHE,KNDGNH_N, &
    &                             KF_FS,KF_UV,KNDGNH,KIN_STRIDES0,KIN0_STRIDES0)
    USE PARKIND_ECTRANS, ONLY: JPIM, JPRB, JPRBT, JPRD, JPIB

    IMPLICIT NONE

    INTEGER(KIND=JPIB), INTENT(IN)    :: KFOUBUF, KIN_SIZE, KIN0_SIZE
    INTEGER(KIND=JPIM), INTENT(IN)    :: KNUMP, KNDGL, KNSMAX, KNDGNH_N
    INTEGER(KIND=JPIM), INTENT(IN)    :: KF_FS, KF_UV, KNDGNH, KIN_STRIDES0, KIN0_STRIDES0
    REAL(KIND=JPRBT),   INTENT(IN)    :: PFOUBUF(KFOUBUF)
    REAL(KIND=JPRBT),   INTENT(INOUT) :: PZINPS(KIN_SIZE), PZINPA(KIN_SIZE)
    REAL(KIND=JPRD),    INTENT(INOUT) :: PZINPS0(KIN0_SIZE), PZINPA0(KIN0_SIZE)
    INTEGER(KIND=JPIM), INTENT(IN)    :: KMYMS(KNUMP)
    INTEGER(KIND=JPIB), INTENT(IN)    :: KOFFSETS_GEMM1(KNUMP+1)
    INTEGER(KIND=JPIM), INTENT(IN)    :: KNPNTGTB1(KNUMP,KNDGL)
    INTEGER(KIND=JPIM), INTENT(IN)    :: KNDGLU(0:KNSMAX)
    REAL(KIND=JPRD),    INTENT(IN)    :: PRW(KNDGNH_N), PRACTHE(KNDGNH_N)

    INTEGER(KIND=JPIB) :: JF, OFFSET1, OFFSET2
    INTEGER(KIND=JPIM) :: KM, ISL, IGLS, JGL, KMLOC
    REAL(KIND=JPRBT) :: PAIA, PAIS

#ifdef OMPGPU
    !$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO COLLAPSE(3) ECTRANS_OMP_DEFAULT_CLAUSE &
    !$OMP& PRIVATE(KM,ISL,IGLS,OFFSET1,OFFSET2,PAIA,PAIS) &
    !$OMP& ECTRANS_DEVICE_ADDR_CLAUSE(PFOUBUF,PZINPA,PZINPS,PZINPA0,PZINPS0) &
    !$OMP& MAP(ECTRANS_MAP_PRESENT_ALLOC:KMYMS,KOFFSETS_GEMM1,KNPNTGTB1,KNDGLU,PRW,PRACTHE) &
    !$OMP& ECTRANS_LOOP_BOUNDS_CLAUSE(KF_FS) FIRSTPRIVATE(KF_UV,KIN_STRIDES0,KIN0_STRIDES0)
#endif
#ifdef ACCGPU
    !$ACC PARALLEL LOOP DEFAULT(NONE) COLLAPSE(3) PRIVATE(KM,ISL,IGLS,OFFSET1,OFFSET2,JGL,PAIA,PAIS) &
    !$ACC&              PRESENT(KMYMS,KOFFSETS_GEMM1,KNPNTGTB1,KNDGLU,PRW,PRACTHE) &
    !$ACC&              FIRSTPRIVATE(KF_FS,KF_UV,KIN_STRIDES0,KIN0_STRIDES0) &
#ifndef _CRAYFTN
    !$ACC& ASYNC(1)
#else
    !$ACC&
#endif
#endif
    DO KMLOC=1,KNUMP
      DO JGL=1,KNDGNH
        DO JF=1,KF_FS*2
          KM = KMYMS(KMLOC)
          ISL = KNDGNH-KNDGLU(KM)+1
          IF (JGL >= ISL) THEN
            !(DO JGL=ISL,KNDGNH)
            IGLS = KNDGL+1-JGL
            OFFSET1 = 2_JPIB*KNPNTGTB1(KMLOC,JGL )*KF_FS
            OFFSET2 = 2_JPIB*KNPNTGTB1(KMLOC,IGLS)*KF_FS
            PAIA = PFOUBUF(OFFSET1+JF)-PFOUBUF(OFFSET2+JF)
            PAIS = PFOUBUF(OFFSET1+JF)+PFOUBUF(OFFSET2+JF)
            IF (JF <= 4*KF_UV) THEN
                ! Multiply in case of velocity
              PAIA = PAIA*REAL(PRACTHE(JGL),JPRBT)
              PAIS = PAIS*REAL(PRACTHE(JGL),JPRBT)
            ENDIF
            IF (KM /= 0) THEN
              PZINPA(JF+(JGL-ISL)*KIN_STRIDES0+KIN_STRIDES0*KOFFSETS_GEMM1(KMLOC))=PAIA*REAL(PRW(JGL),JPRBT)
              PZINPS(JF+(JGL-ISL)*KIN_STRIDES0+KIN_STRIDES0*KOFFSETS_GEMM1(KMLOC))=PAIS*REAL(PRW(JGL),JPRBT)
            ELSEIF (MOD(JF-1,2) == 0) THEN
              ! every other field is sufficient because Im(KM=0) == 0
              PZINPA0((JF-1)/2+1+(JGL-1)*KIN0_STRIDES0)=PAIA*REAL(PRW(JGL),JPRBT)
              PZINPS0((JF-1)/2+1+(JGL-1)*KIN0_STRIDES0)=PAIS*REAL(PRW(JGL),JPRBT)
            ENDIF
          ENDIF
        ENDDO
      ENDDO
    END DO
  END SUBROUTINE TRLTOM_UNPACK_KERNEL

END MODULE TRLTOM_PACK_UNPACK

